// EPL Oracle v4.2 — Head-to-Head Lookup
// Loads precomputed H2H history from data/h2h_lookup.json (generated by python/fetch_historical.py).
// Returns the last 5 meetings between two teams and computes H2H features.

import { readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../logger.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const H2H_PATH = resolve(__dirname, '../../data/h2h_lookup.json');

interface H2HEntry {
  home: string;   // abbreviation of home team in that match
  away: string;   // abbreviation of away team in that match
  hg: number;     // home goals scored
  ag: number;     // away goals scored
  date: string;   // YYYY-MM-DD
}

let _h2h: Record<string, H2HEntry[]> | null = null;

export function loadH2H(): boolean {
  if (!existsSync(H2H_PATH)) {
    logger.warn('H2H lookup not found — run python/fetch_historical.py to generate it');
    return false;
  }
  try {
    _h2h = JSON.parse(readFileSync(H2H_PATH, 'utf-8')) as Record<string, H2HEntry[]>;
    const pairs = Object.keys(_h2h).length;
    logger.info({ pairs }, 'H2H lookup loaded');
    return true;
  } catch (err) {
    logger.warn({ err }, 'Failed to load H2H lookup');
    return false;
  }
}

export interface H2HFeatures {
  h2h_home_win_rate: number;  // fraction of last 5 meetings where the home team (in THIS match) won
  h2h_goal_diff: number;      // average (home team goals - away team goals) in last 5 meetings
}

// League-average defaults (used when no H2H history exists)
const DEFAULTS: H2HFeatures = {
  h2h_home_win_rate: 0.44,  // EPL historical home win rate
  h2h_goal_diff: 0.28,      // typical EPL home goal advantage
};

export function getH2HFeatures(homeAbbr: string, awayAbbr: string): H2HFeatures {
  if (!_h2h) return DEFAULTS;

  // Key is alphabetically sorted so "ARS_LIV" covers both ARS at home vs LIV and vice versa
  const key = [homeAbbr, awayAbbr].sort().join('_');
  const records = _h2h[key];

  if (!records || records.length === 0) return DEFAULTS;

  const recent = records.slice(-5); // last 5 meetings
  let wins = 0;
  let totalDiff = 0;

  for (const r of recent) {
    // Compute goals from THIS match's home team's perspective
    const homeGoals = r.home === homeAbbr ? r.hg : r.ag;
    const awayGoals = r.home === homeAbbr ? r.ag : r.hg;
    if (homeGoals > awayGoals) wins++;
    totalDiff += homeGoals - awayGoals;
  }

  return {
    h2h_home_win_rate: wins / recent.length,
    h2h_goal_diff: totalDiff / recent.length,
  };
}

export function isH2HLoaded(): boolean {
  return _h2h !== null;
}
