// EPL Oracle v4.2 — Gradient Boosting Meta-Model
// Loads serialized GBM trees from data/model/gbm_model.json (generated by python/train_model.py).
// Falls back to Poisson probabilities if model not trained yet.
// Outputs calibrated P(home win), P(draw), P(away win) summing to 1.

import { readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../logger.js';
import type { FeatureVector } from '../types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const MODEL_DIR = resolve(__dirname, '../../data/model');

// Feature names in exact training order (must match python/train_model.py)
export const FEATURE_NAMES = [
  'elo_diff',
  'attack_diff',
  'defense_diff',
  'goal_diff_diff',
  'goals_for_diff',
  'goals_against_diff',
  'net_goals_diff',
  'form_diff',
  'home_form',
  'away_form',
  'position_diff',
  'shots_on_target_diff',
  'possession_diff',
  'clean_sheet_diff',
  'rest_days_diff',
  'home_short_rest',
  'away_short_rest',
  'home_euro_fatigue',
  'away_euro_fatigue',
  'is_neutral',
  'lambda_home',
  'lambda_away',
  'vegas_home_prob',
  'vegas_draw_prob',
  'mc_home_win_prob',
  // v4.2 home/away split features
  'home_att_home',
  'home_def_home',
  'away_att_away',
  'away_def_away',
] as const;

// ─── GBM serialization types ──────────────────────────────────────────────────

interface SerializedTree {
  left: number[];      // left child index (-1 = leaf)
  right: number[];     // right child index (-1 = leaf)
  feature: number[];   // feature index for split (-2 = leaf)
  threshold: number[]; // split threshold
  value: number[];     // leaf value (only meaningful at leaves)
}

interface GBMModel {
  version: string;
  n_features: number;
  feature_names: string[];
  classes: string[];        // e.g. ['away', 'draw', 'home']
  n_classes: number;
  n_estimators: number;
  learning_rate: number;
  init_scores: number[];    // initial log-odds per class (from DummyClassifier prior)
  trees: SerializedTree[][]; // [n_estimators][n_classes]
}

interface ModelScaler {
  mean: number[];
  scale: number[];
  feature_names: string[];
}

interface CalibrationMap {
  x_thresholds: number[];
  y_thresholds: number[];
}

interface ModelMetadata {
  version: string;
  model_type: string;
  train_seasons: string;
  avg_brier: number;
  avg_accuracy: number;
  n_features: number;
  trained_at: string;
}

let _gbm: GBMModel | null = null;
let _scaler: ModelScaler | null = null;
let _calibrationHome: CalibrationMap | null = null;
let _calibrationDraw: CalibrationMap | null = null;
let _calibrationAway: CalibrationMap | null = null;
let _metadata: ModelMetadata | null = null;

// ─── Load model artifacts ─────────────────────────────────────────────────────

export function loadModel(): boolean {
  const gbmPath    = resolve(MODEL_DIR, 'gbm_model.json');
  const scalerPath = resolve(MODEL_DIR, 'scaler.json');
  const metaPath   = resolve(MODEL_DIR, 'metadata.json');

  if (!existsSync(gbmPath) || !existsSync(scalerPath)) {
    return false;
  }

  try {
    _gbm    = JSON.parse(readFileSync(gbmPath, 'utf-8')) as GBMModel;
    _scaler = JSON.parse(readFileSync(scalerPath, 'utf-8')) as ModelScaler;

    for (const [name, path] of [
      ['home', resolve(MODEL_DIR, 'calibration_home.json')],
      ['draw', resolve(MODEL_DIR, 'calibration_draw.json')],
      ['away', resolve(MODEL_DIR, 'calibration_away.json')],
    ] as [string, string][]) {
      if (existsSync(path)) {
        const cal = JSON.parse(readFileSync(path, 'utf-8')) as CalibrationMap;
        if (name === 'home') _calibrationHome = cal;
        else if (name === 'draw') _calibrationDraw = cal;
        else _calibrationAway = cal;
      }
    }

    if (existsSync(metaPath)) {
      _metadata = JSON.parse(readFileSync(metaPath, 'utf-8')) as ModelMetadata;
    }

    logger.info(
      { version: _metadata?.version, type: _metadata?.model_type, brier: _metadata?.avg_brier },
      'GBM model loaded',
    );
    return true;
  } catch (err) {
    logger.warn({ err }, 'Failed to load GBM model — falling back to Poisson');
    _gbm = null; _scaler = null;
    return false;
  }
}

export function isModelLoaded(): boolean {
  return _gbm !== null && _scaler !== null;
}

export function getModelInfo(): ModelMetadata | null {
  return _metadata;
}

// ─── Feature vector → standardized array ──────────────────────────────────────

function featureToArray(features: FeatureVector): number[] {
  return FEATURE_NAMES.map(name => {
    const val = features[name as keyof FeatureVector];
    return typeof val === 'number' ? val : 0;
  });
}

function standardize(x: number[], scaler: ModelScaler): number[] {
  return x.map((val, i) => {
    const mean  = scaler.mean[i]  ?? 0;
    const scale = scaler.scale[i] ?? 1;
    return scale === 0 ? 0 : (val - mean) / scale;
  });
}

// ─── GBM tree traversal ───────────────────────────────────────────────────────

const TREE_LEAF = -1; // sklearn constant for leaf nodes

function traverseTree(tree: SerializedTree, x: number[]): number {
  let node = 0;
  while (tree.left[node] !== TREE_LEAF) {
    const featureIdx = tree.feature[node];
    const threshold  = tree.threshold[node];
    node = (x[featureIdx] ?? 0) <= threshold ? tree.left[node] : tree.right[node];
  }
  return tree.value[node];
}

// ─── Softmax ──────────────────────────────────────────────────────────────────

function softmax(logits: number[]): number[] {
  const maxLogit = Math.max(...logits);
  const exps = logits.map(l => Math.exp(l - maxLogit));
  const sum  = exps.reduce((a, b) => a + b, 0);
  return exps.map(e => e / sum);
}

// ─── Isotonic calibration ─────────────────────────────────────────────────────

function applyCalibration(prob: number, cal: CalibrationMap | null): number {
  if (!cal) return prob;
  const { x_thresholds, y_thresholds } = cal;
  if (prob <= x_thresholds[0]) return y_thresholds[0];
  if (prob >= x_thresholds[x_thresholds.length - 1]) return y_thresholds[y_thresholds.length - 1];
  for (let i = 1; i < x_thresholds.length; i++) {
    if (prob <= x_thresholds[i]) {
      const t = (prob - x_thresholds[i - 1]) / (x_thresholds[i] - x_thresholds[i - 1]);
      return y_thresholds[i - 1] + t * (y_thresholds[i] - y_thresholds[i - 1]);
    }
  }
  return prob;
}

// ─── Main predict function ────────────────────────────────────────────────────

export function predict(
  features: FeatureVector,
  mcHomeWin: number,
  mcDraw: number,
  mcAwayWin: number,
): { home: number; draw: number; away: number } {
  if (!_gbm || !_scaler) {
    return { home: mcHomeWin, draw: mcDraw, away: mcAwayWin };
  }

  try {
    const rawFeatures = featureToArray(features);
    const scaled = standardize(rawFeatures, _scaler);

    // GBM inference: start from init_scores, accumulate tree contributions
    const scores = [..._gbm.init_scores]; // shape: [n_classes]
    const lr = _gbm.learning_rate;

    for (const stage of _gbm.trees) {
      for (let k = 0; k < _gbm.n_classes; k++) {
        scores[k] += lr * traverseTree(stage[k], scaled);
      }
    }

    // Softmax → class probabilities
    const rawProbs = softmax(scores);

    // Map class names to home/draw/away (GBM classes_ may be alphabetical: away, draw, home)
    const classOrder = _gbm.classes; // e.g. ['away', 'draw', 'home']
    const rawHome = rawProbs[classOrder.indexOf('home')] ?? rawProbs[0];
    const rawDraw = rawProbs[classOrder.indexOf('draw')] ?? rawProbs[1];
    const rawAway = rawProbs[classOrder.indexOf('away')] ?? rawProbs[2];

    // Per-class isotonic calibration
    let calHome = applyCalibration(rawHome, _calibrationHome);
    let calDraw = applyCalibration(rawDraw, _calibrationDraw);
    let calAway = applyCalibration(rawAway, _calibrationAway);

    // Re-normalize to sum to 1
    const total = calHome + calDraw + calAway;
    if (total > 0) {
      calHome /= total;
      calDraw /= total;
      calAway /= total;
    }

    return {
      home: Math.max(0.02, Math.min(0.95, calHome)),
      draw: Math.max(0.02, Math.min(0.95, calDraw)),
      away: Math.max(0.02, Math.min(0.95, calAway)),
    };
  } catch (err) {
    logger.debug({ err }, 'GBM predict error — falling back to Poisson');
    return { home: mcHomeWin, draw: mcDraw, away: mcAwayWin };
  }
}
