// EPL Oracle v4.1 — Logistic Regression Meta-Model (Multi-class)
// Loads coefficients + scaler from data/model/ (generated by python/train_model.py).
// Falls back to Poisson probabilities if model not trained yet.
// Outputs calibrated P(home win), P(draw), P(away win) summing to 1.

import { readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../logger.js';
import type { FeatureVector } from '../types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const MODEL_DIR = resolve(__dirname, '../../data/model');

// Feature names in exact training order (must match python/train_model.py)
export const FEATURE_NAMES = [
  'elo_diff',
  'attack_diff',
  'defense_diff',
  'goal_diff_diff',
  'goals_for_diff',
  'goals_against_diff',
  'net_goals_diff',
  'form_diff',
  'home_form',
  'away_form',
  'position_diff',
  'shots_on_target_diff',
  'possession_diff',
  'clean_sheet_diff',
  'rest_days_diff',
  'home_short_rest',
  'away_short_rest',
  'home_euro_fatigue',
  'away_euro_fatigue',
  'is_neutral',
  'lambda_home',
  'lambda_away',
  'vegas_home_prob',
  'vegas_draw_prob',
  'mc_home_win_prob',
] as const;

// Multi-class coefficients: 3 classes × n_features
interface MultiClassCoefficients {
  classes: ['home', 'draw', 'away'];
  intercepts: [number, number, number];
  coefficients: [number[], number[], number[]];  // [home_coefs, draw_coefs, away_coefs]
  feature_names: string[];
}

interface ModelScaler {
  mean: number[];
  scale: number[];
  feature_names: string[];
}

interface CalibrationMap {
  x_thresholds: number[];
  y_thresholds: number[];
}

interface ModelMetadata {
  version: string;
  train_seasons: string;
  avg_brier: number;
  avg_accuracy: number;
  n_features: number;
  trained_at: string;
}

let _model: MultiClassCoefficients | null = null;
let _scaler: ModelScaler | null = null;
let _calibrationHome: CalibrationMap | null = null;
let _calibrationDraw: CalibrationMap | null = null;
let _calibrationAway: CalibrationMap | null = null;
let _metadata: ModelMetadata | null = null;

// ─── Load model artifacts ─────────────────────────────────────────────────────

export function loadModel(): boolean {
  const coeffPath = resolve(MODEL_DIR, 'coefficients.json');
  const scalerPath = resolve(MODEL_DIR, 'scaler.json');
  const calHomePath = resolve(MODEL_DIR, 'calibration_home.json');
  const calDrawPath = resolve(MODEL_DIR, 'calibration_draw.json');
  const calAwayPath = resolve(MODEL_DIR, 'calibration_away.json');
  const metaPath = resolve(MODEL_DIR, 'metadata.json');

  if (!existsSync(coeffPath) || !existsSync(scalerPath)) {
    return false;
  }

  try {
    _model = JSON.parse(readFileSync(coeffPath, 'utf-8')) as MultiClassCoefficients;
    _scaler = JSON.parse(readFileSync(scalerPath, 'utf-8')) as ModelScaler;
    if (existsSync(calHomePath)) _calibrationHome = JSON.parse(readFileSync(calHomePath, 'utf-8')) as CalibrationMap;
    if (existsSync(calDrawPath)) _calibrationDraw = JSON.parse(readFileSync(calDrawPath, 'utf-8')) as CalibrationMap;
    if (existsSync(calAwayPath)) _calibrationAway = JSON.parse(readFileSync(calAwayPath, 'utf-8')) as CalibrationMap;
    if (existsSync(metaPath)) _metadata = JSON.parse(readFileSync(metaPath, 'utf-8')) as ModelMetadata;
    logger.info({ version: _metadata?.version, brier: _metadata?.avg_brier }, 'ML model loaded');
    return true;
  } catch (err) {
    logger.warn({ err }, 'Failed to load ML model — falling back to Poisson');
    _model = null; _scaler = null;
    return false;
  }
}

export function isModelLoaded(): boolean {
  return _model !== null && _scaler !== null;
}

export function getModelInfo(): ModelMetadata | null {
  return _metadata;
}

// ─── Feature vector → array ───────────────────────────────────────────────────

function featureToArray(features: FeatureVector): number[] {
  return FEATURE_NAMES.map(name => {
    const val = features[name as keyof FeatureVector];
    return typeof val === 'number' ? val : 0;
  });
}

// ─── Standardize ─────────────────────────────────────────────────────────────

function standardize(x: number[], scaler: ModelScaler): number[] {
  return x.map((val, i) => {
    const mean = scaler.mean[i] ?? 0;
    const scale = scaler.scale[i] ?? 1;
    return scale === 0 ? 0 : (val - mean) / scale;
  });
}

// ─── Softmax ──────────────────────────────────────────────────────────────────

function softmax(logits: number[]): number[] {
  const maxLogit = Math.max(...logits);
  const exps = logits.map(l => Math.exp(l - maxLogit));
  const sum = exps.reduce((a, b) => a + b, 0);
  return exps.map(e => e / sum);
}

// ─── Isotonic calibration ─────────────────────────────────────────────────────

function applyCalibration(prob: number, cal: CalibrationMap | null): number {
  if (!cal) return prob;
  const { x_thresholds, y_thresholds } = cal;
  if (prob <= x_thresholds[0]) return y_thresholds[0];
  if (prob >= x_thresholds[x_thresholds.length - 1]) return y_thresholds[y_thresholds.length - 1];
  for (let i = 1; i < x_thresholds.length; i++) {
    if (prob <= x_thresholds[i]) {
      const t = (prob - x_thresholds[i - 1]) / (x_thresholds[i] - x_thresholds[i - 1]);
      return y_thresholds[i - 1] + t * (y_thresholds[i] - y_thresholds[i - 1]);
    }
  }
  return prob;
}

// ─── Main predict function ────────────────────────────────────────────────────

export function predict(
  features: FeatureVector,
  mcHomeWin: number,
  mcDraw: number,
  mcAwayWin: number,
): { home: number; draw: number; away: number } {
  if (!_model || !_scaler) {
    return { home: mcHomeWin, draw: mcDraw, away: mcAwayWin };
  }

  try {
    const rawFeatures = featureToArray(features);
    const scaled = standardize(rawFeatures, _scaler);

    // Multi-class logistic regression (one-vs-rest softmax)
    const logits = _model.intercepts.map((intercept, classIdx) => {
      const coefs = _model!.coefficients[classIdx] ?? [];
      return intercept + scaled.reduce((sum, val, i) => sum + val * (coefs[i] ?? 0), 0);
    });

    const [rawHome, rawDraw, rawAway] = softmax(logits);

    // Apply per-class isotonic calibration
    let calHome = applyCalibration(rawHome, _calibrationHome);
    let calDraw = applyCalibration(rawDraw, _calibrationDraw);
    let calAway = applyCalibration(rawAway, _calibrationAway);

    // Re-normalize to sum to 1
    const total = calHome + calDraw + calAway;
    if (total > 0) {
      calHome /= total;
      calDraw /= total;
      calAway /= total;
    }

    return {
      home: Math.max(0.02, Math.min(0.95, calHome)),
      draw: Math.max(0.02, Math.min(0.95, calDraw)),
      away: Math.max(0.02, Math.min(0.95, calAway)),
    };
  } catch (err) {
    logger.debug({ err }, 'ML predict error — falling back to Poisson');
    return { home: mcHomeWin, draw: mcDraw, away: mcAwayWin };
  }
}
